name: Vote Auto

on:
  workflow_dispatch:

jobs:
  vote:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1,2,3,4,5]
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: pip install curl_cffi -q
      - name: Vote
        run: python vote_cffi.py
        env:
          PG_VOTES: "30"
